name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: PHPUnit Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
        ports:
          - 3306:3306

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          coverage: xdebug
          tools: composer

      # Install dependencies
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      # Run PHPUnit tests with coverage
      - name: Run tests
        run: |
          mkdir -p build/logs
          vendor/bin/simple-phpunit --coverage-clover build/logs/coverage.xml

      # Upload PHPUnit coverage report as artifacts
      - name: Upload coverage for analysis
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: build/logs/coverage.xml

      # Display coverage to GitHub summary (optional step)
      - name: Publish code coverage summary
        uses: shivammathur/php-coverage@v2
        with:
          clover: build/logs/coverage.xml