name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer
          coverage: xdebug

      # 3. Install dependencies
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      # 4. Run tests with coverage
      - name: Run PHPUnit tests
        run: |
          mkdir -p build/logs
          vendor/bin/phpunit --coverage-html build/coverage-html

      # 5. Upload test coverage report as an artifact
      - name: Upload PHPUnit coverage
        uses: actions/upload-artifact@v3
        with:
          name: html-coverage
          path: build/coverage-html